FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY MaIN.RAG.Demo/*.csproj ./MaIN.RAG.Demo/

RUN dotnet restore ./MaIN.RAG.Demo/MaIN.RAG.Demo.csproj

COPY . ./
RUN dotnet publish ./MaIN.RAG.Demo/MaIN.RAG.Demo.csproj -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "MaIN.RAG.Demo.dll"]